#!/usr/bin/env bash
version=$(git describe --tags --abbrev=0 | sed 's/^.//')
version=104.10

./gradlew server:dist -Pbuildversion=$version

scp server/build/libs/server-release.jar root@mindustry.nydus.app:/root/server-release.jar

ssh root@mindustry.nydus.app cp /root/server-release.jar /root/nydus/server-release.jar
ssh root@mindustry.nydus.app cp /root/server-release.jar /root/veteran/server-release.jar
ssh root@mindustry.nydus.app cp /root/server-release.jar /root/limbo/server-release.jar
ssh root@mindustry.nydus.app cp /root/server-release.jar /root/silicon/server-release.jar

ssh root@mindustry.nydus.app rm /root/server-release.jar
